In [132]:
#!python -m pip install --upgrade pip
#%pip install pandas matplotlib seaborn scikit-learn openpyxl tensorflow xgboost aif360
#%pip install "aif360[Reductions, inFairness]"

In [133]:
import json
import pandas as pd
from pprint import pprint
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

import tensorflow as tf
from tensorflow.keras.models import Sequential # type: ignore
from tensorflow.keras.layers import Dense, BatchNormalization # type: ignore

from aif360.datasets import StandardDataset
from fairlearn.preprocessing import CorrelationRemover
from aif360.algorithms.inprocessing import GerryFairClassifier
from fairlearn.postprocessing import ThresholdOptimizer

random_seed = 15

In [134]:
PATH = 'C:/Users/andre/Desktop/ProjectWork_AEQUITAS_AKKODIS/'
df = (
    pd.read_excel(PATH + 'data/Dataset_Preprocessed.xlsx')
)
df.head()

,Technical Skills,Comunication,Maturity,Dynamism,Mobility,English,Candidate State_encoded,Event_Feedback_encoded,Residence City_encoded,Residence Province_encoded,...,Sector_encoded,Job Family Hiring_encoded,Job Title Hiring_encoded,Overall_encoded,Minimum Ral_encoded,Ral Maximum_encoded,Study Level_encoded,Current Ral_encoded,Expected Ral_encoded,Status_encoded
0,3,2,3,3,2,4,6,11,689,102,...,1,3,5,5,7,9,6,4,5,1
1,2,2,2,2,2,3,4,10,218,8,...,0,4,8,0,1,1,0,5,6,0
2,2,2,2,2,2,3,3,9,157,22,...,2,4,8,0,1,1,0,1,1,1
3,2,2,2,2,2,3,3,11,636,57,...,13,4,8,0,1,1,0,3,3,1
4,3,2,2,3,1,1,2,11,39,98,...,1,4,8,3,1,1,0,1,5,0

In [135]:
with open(PATH + 'data/encoding_mappings.json', 'r') as f:
    encoding_mappings = json.load(f)
pprint(encoding_mappings)

{'Age Range': {'20 - 25 years': 1,
               '26 - 30 years': 2,
               '31 - 35 years': 3,
               '36 - 40 years': 4,
               '40 - 45 years': 5,
               '< 20 years': 0,
               '> 45 years': 6},
 'Candidate State': {'Economic proposal': 5,
                     'First contact': 1,
                     'Hired': 6,
                     'Imported': 0,
                     'In selection': 2,
                     'QM': 3,
                     'Vivier': 4},
 'Current Ral': {'+ 50 K': 18,
                 '- 20 K': 2,
                 '20-22 K': 3,
                 '22-24 K': 4,
                 '24-26 K': 5,
                 '26-28 K': 6,
                 '28-30 K': 7,
                 '30-32 K': 8,
                 '32-34 K': 9,
                 '34-36 K': 10,
                 '36-38 K': 11,
                 '38-40 K': 12,
                 '40-42 K': 13,
                 '42-44 K': 14,
                 '44-46 K': 15,
                 '46-48 K': 16,
                 '48-50 K': 17,
                 'Not Specified': 1,
                 'Not available': 0},
 'European Residence': {'No': 0, 'Yes': 1},
 'Event_Feedback': {'KO (language skills)': 0,
                    'KO (lost availability)': 1,
                    'KO (manager)': 2,
                    'KO (mobility)': 3,
                    'KO (opportunity closed)': 4,
                    'KO (proposed renunciation)': 5,
                    'KO (ral)': 6,
                    'KO (retired)': 7,
                    'KO (seniority)': 8,
                    'KO (technical skills)': 9,
                    'Not Specified': 10,
                    'OK': 11,
                    'OK (hired)': 12,
                    'OK (live)': 13,
                    'OK (other candidate)': 14,
                    'OK (waiting for departure)': 15},
 'Expected Ral': {'+ 50 K': 18,
                  '- 20 K': 2,
                  '20-22 K': 3,
                  '22-24 K': 4,
                  '24-26 K': 5,
                  '26-28 K': 6,
                  '28-30 K': 7,
                  '30-32 K': 8,
                  '32-34 K': 9,
                  '34-36 K': 10,
                  '36-38 K': 11,
                  '38-40 K': 12,
                  '40-42 K': 13,
                  '42-44 K': 14,
                  '44-46 K': 15,
                  '46-48 K': 16,
                  '48-50 K': 17,
                  'Not Specified': 1,
                  'Not available': 0},
 'Italian Residence': {'No': 0, 'Yes': 1},
 'Job Family Hiring': {'Business & Sales': 0,
                       'Business Management & Sales': 1,
                       'Enabling Function': 2,
                       'Engineering': 3,
                       'Not Specified': 4,
                       'Support': 5,
                       'Talent Acquisition': 6,
                       'Tech Consulting & Solutions': 7},
 'Job Title Hiring': {'???': 0,
                      'Advanced Business Manager': 1,
                      'Advanced Consultant': 2,
                      'Business Manager': 3,
                      'Business Unit Director': 4,
                      'Consultant': 5,
                      'Junior Business Manager': 6,
                      'Junior Consultant': 7,
                      'Not Specified': 8,
                      'Pharmaceutical Consultant': 9,
                      'Qualified Consultant': 10,
                      'Senior Consultant': 11,
                      'Senior Sales Manager': 12,
                      'Sourcing Specialist': 13,
                      'Support': 14,
                      'Support Advanced': 15,
                      'Talent Acquisition Specialist': 16,
                      'Team Leader': 17,
                      'Technician': 18},
 'Minimum Ral': {'+50K': 19,
                 '- 20K': 2,
                 '20-22K': 4,
                 '20K': 3,
                 '22-24K': 5,
                 '24-26K': 6,
                 '26-28K': 7,
                 '28-30K': 8,
                 '30-32K': 9,
                 '32-34K': 10,
                 '34-36K': 11,
                 '36-38K': 12,
                 '38-40K': 13,
                 '40-42K': 14,
                 '42-44K': 15,
                 '44-46K': 16,
                 '46-48K': 17,
                 '48-50K': 18,
                 'Not Avail.': 0,
                 'Not Specified': 1},
 'Overall': {'1 - Low': 2,
             '2 - Medium': 4,
             '3 - High': 6,
             '4 - Top': 8,
             'Not Specified': 0,
             '~ 1 - Low': 1,
             '~ 2 - Medium': 3,
             '~ 3 - High': 5,
             '~ 4 - Top': 7},
 'Protected Category': {'Not a protected category': 0, 'Yes': 1},
 'Ral Maximum': {'+50K': 19,
                 '- 20K': 2,
                 '20-22K': 4,
                 '20K': 3,
                 '22-24K': 5,
                 '24-26K': 6,
                 '26-28K': 7,
                 '28-30K': 8,
                 '30-32K': 9,
                 '32-34K': 10,
                 '34-36K': 11,
                 '36-38K': 12,
                 '38-40K': 13,
                 '40-42K': 14,
                 '42-44K': 15,
                 '44-46K': 16,
                 '46-48K': 17,
                 '48-50k': 18,
                 'Not Avail.': 0,
                 'Not Specified': 1},
 'Residence City': {'ABANO TERME': 0,
                    'ABBASANTA': 1,
                    'ABBIATEGRASSO': 2,
                    'ACCEPTANCE': 3,
                    'ACERRA': 4,
                    "ACI SANT'ANTONIO": 5,
                    'ACQUAVIVA DELLE FONTI': 6,
                    'ACQUAVIVA PICENA': 7,
                    'ACQUI TERME': 8,
                    'ADRIATIC DAWN': 9,
                    'AFFI': 10,
                    'AFFORI': 11,
                    'AFRAGOLA': 12,
                    'AGRATE BRIANZA': 13,
                    'AGRATE CONTURBIA': 14,
                    'AGRIGENTO': 15,
                    'ALBA': 16,
                    'ALBIATE': 17,
                    'ALBINEA': 18,
                    'ALBINO': 19,
                    'ALBUSCIAGO': 20,
                    'ALESSANDRIA': 21,
                    'ALGHERO': 22,
                    'ALIFE': 23,
                    'ALLUMIERE': 24,
                    'ALPIGNANO': 25,
                    'ALSENO': 26,
                    'ALTAMURA': 27,
                    'ALTOFONTE': 28,
                    'ALTOMONTE': 29,
                    'AMANTEA': 30,
                    'AMELIA': 31,
                    'ANCONA': 32,
                    'ANDEZENO': 33,
                    'ANDRIA': 34,
                    'ANGERA': 35,
                    'ANGRI': 36,
                    'AOSTA': 37,
                    'APRILIA': 38,
                    'ARA': 39,
                    'ARCONATE': 40,
                    'ARENZANO': 41,
                    'AREZZO': 42,
                    'ARI': 43,
                    'ARLUNO': 44,
                    'ARMUNGIA': 45,
                    'ARZACHENA': 46,
                    "ARZAGO D'ADDA": 47,
                    'ARZIGNANO': 48,
                    'ASCOLI PICENO': 49,
                    'ASCOLI SATRIANO': 50,
                    'ASSAGO': 51,
                    'ASTI': 52,
                    'AUGUST': 53,
                    'AULLA': 54,
                    'AVELLINO': 55,
                    'AVERSA': 56,
                    'AVETRANA': 57,
                    'AVEZZANO': 58,
                    'AVIGLIANA': 59,
                    'AVOLA': 60,
                    'AZZANO SAN PAOLO': 61,
                    'AZZATE': 62,
                    'BAGNO A RIPOLI': 63,
                    'BAIANO': 64,
                    'BALDISSERO TORINESE': 65,
                    'BALM': 66,
                    'BARBERINO DI MUGELLO': 67,
                    'BARCELONA POZZO DI GOTTO': 68,
                    'BARDI': 69,
                    'BARLETTA': 70,
                    'BASIGLIO': 71,
                    'BASILIANO': 72,
                    'BATTIPAGLIA': 73,
                    'BAUNEI': 74,
                    'BEINASCO': 75,
                    'BELLUNO': 76,
                    'BENEVENTO': 77,
                    'BERGAMO': 78,
                    'BERNALDA': 79,
                    'BERRA': 80,
                    'BEVAGNA': 81,
                    'BIBBIENA': 82,
                    'BIELLA': 83,
                    'BIENTINA': 84,
                    'BINASCO': 85,
                    'BISCEGLIE': 86,
                    'BITETTO': 87,
                    'BITONTO': 88,
                    'BITTER': 89,
                    'BLACKBOARD': 90,
                    'BOLLATE': 91,
                    'BOLLENGO': 92,
                    'BOLOGNA': 93,
                    'BOLOGNOLA': 94,
                    'BOLZANO': 95,
                    'BONITO': 96,
                    'BORGO MANTOVANO': 97,
                    'BORGO PRIOLO': 98,
                    'BORGO SAN LORENZO': 99,
                    'BORGOMASINO': 100,
                    'BORGONE SUSA': 101,
                    'BORNATE': 102,
                    'BOSCOREALE': 103,
                    'BOSCOTRECASE': 104,
                    'BOTTICINO': 105,
                    'BOVILLE': 106,
                    'BOVISIO-MASCIAGO': 107,
                    'BRACCIANO': 108,
                    'BREDA DI PIAVE': 109,
                    'BRESCIA': 110,
                    'BRESSO': 111,
                    "BRIANO'S VILLA": 112,
                    'BRICHERASIO': 113,
                    'BRIDGE': 114,
                    "BRIGNANO GERA D'ADDA": 115,
                    'BRINDISI': 116,
                    'BRONTE': 117,
                    'BRUGHERIO': 118,
                    'BRUSCIANO': 119,
                    'BUONALBERGO': 120,
                    'BUSCA': 121,
                    'BUSSOLENO': 122,
                    'BUSTIGHERA': 123,
                    'BUSTO ARSIZIO': 124,
                    'CALCINAIA': 125,
                    'CALENZANO': 126,
                    'CALTANISSETTA': 127,
                    'CALVIZZANO': 128,
                    'CAMAIORE': 129,
                    'CAMBIANO': 130,
                    'CAMPAGNANO DI ROMA': 131,
                    'CAMPI BISENZIO': 132,
                    'CAMPOBASSO': 133,
                    'CANDIOLO': 134,
                    'CANOSA DI PUGLIA': 135,
                    'CAPANNOLI': 136,
                    'CAPANNORI': 137,
                    'CAPISTRELLO': 138,
                    'CAPOTERRA': 139,
                    'CAPRAROLA': 140,
                    'CAPUA': 141,
                    'CAPURSO': 142,
                    'CARBONIA': 143,
                    'CARMAGNOLA': 144,
                    'CARNATE': 145,
                    'CAROSINO': 146,
                    'CAROVIGNO': 147,
                    'CARPI': 148,
                    'CARUGATE': 149,
                    'CASALBORDINO': 150,
                    'CASALECCHIO DI RENO': 151,
                    'CASALGRANDE': 152,
                    'CASALGRASSO': 153,
                    'CASALMORO': 154,
                    'CASALNUOVO DI NAPLES': 155,
                    'CASAMASSIMA': 156,
                    'CASERTA': 157,
                    'CASORIA': 158,
                    "CASSANO D'ADDA": 159,
                    'CASSINO': 160,
                    'CASTEL MAGGIORE': 161,
                    'CASTEL SAN GIORGIO': 162,
                    'CASTEL VOLTURNO': 163,
                    'CASTELFIORENTINO': 164,
                    'CASTELFRANCI': 165,
                    'CASTELFRANCO DI SOTTO': 166,
                    'CASTELLAMMARE DI STABIA': 167,
                    'CASTELLANA GROTTE': 168,
                    'CASTELLETTO ABOVE TICINO': 169,
                    'CASTELNUOVO DELLA DAUNIA': 170,
                    'CASTELTERMINI': 171,
                    'CASTELVETRANO': 172,
                    'CASTENASO': 173,
                    'CATANIA': 174,
                    'CATANZARO': 175,
                    'CATHOLIC': 176,
                    "CAVA DE' TIRRENI": 177,
                    'CAVEZZO': 178,
                    'CECINA': 179,
                    'CEGGIA': 180,
                    'CEGLIE MESSAPICA': 181,
                    'CELANO': 182,
                    'CELLINO SAN MARCO': 183,
                    'CENTO': 184,
                    'CERCOLA': 185,
                    'CERIANO LAGHETTO': 186,
                    'CERIGNOLA': 187,
                    'CERNUSCO SUL NAVIGLIO': 188,
                    'CERRO AL LAMBRO': 189,
                    'CERVERE': 190,
                    'CESANO BOSCONE': 191,
                    'CESENA': 192,
                    'CHANNEL': 193,
                    'CHIERI': 194,
                    'CHIETI': 195,
                    'CHIVASSO': 196,
                    'CHORS': 197,
                    'CIAMPINO': 198,
                    'CINISELLO BALSAMO': 199,
                    "CIRIE'": 200,
                    'CISERANO': 201,
                    'CISLAGO': 202,
                    'CISTERNA DI LATINA': 203,
                    "CITTA' SANT'ANGELO": 204,
                    'CIVITANOVA MARCHE': 205,
                    'COAZZE': 206,
                    'CODOGNO': 207,
                    'CODROIPO': 208,
                    "COLLE DI VAL D'ELSA": 209,
                    'COLLEFERRO': 210,
                    'COLLEGNO': 211,
                    'COLOGNO MONZESE': 212,
                    'COMABBIO': 213,
                    'COMISO': 214,
                    'COMO': 215,
                    'CONCORDIA ON THE SECCHIA': 216,
                    'CONEGLIANO': 217,
                    'CONVERSANO': 218,
                    'CORATO': 219,
                    'CORBETTA': 220,
                    'CORINALDO': 221,
                    'CORSICO': 222,
                    'COSENZA': 223,
                    'CREAM': 224,
                    'CREMONA': 225,
                    'CRISPANO': 226,
                    'CRISPIANO': 227,
                    'CROTONE': 228,
                    'CUGLIATE-FABIASCO': 229,
                    'CUNEO': 230,
                    "CUORGNE'": 231,
                    'CUPRAMONTANA': 232,
                    'CURTI': 233,
                    'CUSANO MILANINO': 234,
                    'CUTRO': 235,
                    'DAIRAGO': 236,
                    'DALMINE': 237,
                    'DESENZANO DEL GARDA': 238,
                    'DESIO': 239,
                    'DINNER BELOW': 240,
                    'DISO': 241,
                    'DORNO': 242,
                    'DRAGONS': 243,
                    'DRONERO': 244,
                    'DRUENTO': 245,
                    'EBOLI': 246,
                    'EMPOLI': 247,
                    'ENGRAVED IN THE ARNO VALLEY': 248,
                    'ENNA': 249,
                    'ENTRATICO': 250,
                    'ERICE': 251,
                    'FAENZA': 252,
                    'FANO': 253,
                    'FARMHOUSE': 254,
                    'FASANO': 255,
                    'FELIZZANO': 256,
                    'FERENTILLO': 257,
                    'FERENTINO': 258,
                    'FERMO': 259,
                    'FERRANDINA': 260,
                    'FIANO ROMANO': 261,
                    'FIDENZA': 262,
                    'FIORANO MODENESE': 263,
                    "FIORENZUOLA D'ARDA": 264,
                    'FIUMICINO': 265,
                    'FLORENCE': 266,
                    'FOGGIA': 267,
                    'FOLLO': 268,
                    'FONTANAROSA': 269,
                    'FORENZA': 270,
                    'FORIO': 271,
                    "FORLI'": 272,
                    'FORMELLO': 273,
                    'FORMIA': 274,
                    'FORTRESS': 275,
                    'FOSSA': 276,
                    'FOURTH': 277,
                    'FRAGAGNANO': 278,
                    'FRANCAVILLA FONTANA': 279,
                    'FRASCATI': 280,
                    'FRIGNANO': 281,
                    'FROSINONE': 282,
                    'GAGGIANO': 283,
                    'GAGLIANICO': 284,
                    'GALATINA': 285,
                    'GAMBETTOLA': 286,
                    'GARDONE VAL TROMPIA': 287,
                    'GARLASCO': 288,
                    'GELA': 289,
                    'GENOA': 290,
                    'GENONI': 291,
                    'GHEDI': 292,
                    'GIAVENO': 293,
                    'GIFFONI VALLE PIANA': 294,
                    'GINOSA': 295,
                    'GIOIA DEL COLLE': 296,
                    'GIOVINAZZO': 297,
                    'GIUGLIANO IN CAMPANIA': 298,
                    'GIUSSANO': 299,
                    'GONZAGA': 300,
                    'GORIZIA': 301,
                    'GORLE': 302,
                    'GRAGNANO': 303,
                    'GRANTORTO': 304,
                    'GRASSANO': 305,
                    'GRAVINA IN PUGLIA': 306,
                    'GREVE IN CHIANTI': 307,
                    'GRONTARDO': 308,
                    'GROTTAGLIE': 309,
                    'GROTTOLE': 310,
                    'GRUGLIASCO': 311,
                    'GRUMO APPULA': 312,
                    'GUALDO TADINO': 313,
                    'GUARENE': 314,
                    'GUBBIO': 315,
                    'GUDO VISCONTI': 316,
                    'GUIDONIA MONTECELIO': 317,
                    'GUSSAGO': 318,
                    'GUSSOLA': 319,
                    'HOSPITALETTO': 320,
                    'IGLESIAS': 321,
                    'IMOLA': 322,
                    'IMPERIA': 323,
                    'IRSINA': 324,
                    'ISERNIA': 325,
                    'ISLAND OF FEMALE': 326,
                    'ISPICA': 327,
                    'IVREA': 328,
                    'JERAGO WITH ORAGO': 329,
                    'JESOLO': 330,
                    "L'AQUILA": 331,
                    'LA SPEZIA': 332,
                    'LADISPOLI': 333,
                    'LAMEZIA TERME': 334,
                    'LANCIANO': 335,
                    'LASTRA A SIGNA': 336,
                    'LATERZA': 337,
                    'LATIANO': 338,
                    'LATINA': 339,
                    'LAURIA': 340,
                    'LECCE': 341,
                    'LECCO': 342,
                    'LEGNAGO': 343,
                    'LEGNANO': 344,
                    'LEINI': 345,
                    'LENNO': 346,
                    'LERICI': 347,
                    'LIGURIAN STONE': 348,
                    'LIMBIATE': 349,
                    'LISSONE': 350,
                    'LIVORNO': 351,
                    'LOCATE VARESINO': 352,
                    'LODI': 353,
                    'LONATE POZZOLO': 354,
                    'LORETO APRUTINO': 355,
                    'LOVED': 356,
                    'LOWER NOCERA': 357,
                    'LOWER VENUE': 358,
                    'LUCCA': 359,
                    'LUCERA': 360,
                    'LUCERNATE': 361,
                    'LUINO': 362,
                    'LUPIA CAMPAIGN': 363,
                    'LURANO': 364,
                    'MACERATA': 365,
                    'MACHERIO': 366,
                    'MADDALONI': 367,
                    'MAGENTA': 368,
                    'MALAGNINO': 369,
                    'MALNATE': 370,
                    'MALTIGNANO': 371,
                    'MANDURIA': 372,
                    'MANFREDONIA': 373,
                    'MANTOVA': 374,
                    'MARCH': 375,
                    'MARGHERITA DI SAVOIA': 376,
                    'MARSALA': 377,
                    'MARTANO': 378,
                    'MARTELLAGO': 379,
                    'MARTINA FRANCA': 380,
                    'MARTINSICURO': 381,
                    "MASERA' DI PADOVA": 382,

## Train

In [136]:
target = 'Status_encoded'
sensitive = 'Sex_encoded'

### Dataset Preparation

In [137]:
df = shuffle(df, random_state=random_seed)

X = df.copy()
y = df[target]
s = df[sensitive]
X_train_split, X_test_split, y_train_split, y_test_split, s_train_split, s_test_split = train_test_split(X, y, s, test_size=0.2, random_state=random_seed, stratify=y)

In [138]:
train_df = X_train_split.copy()
train_df[target] = y_train_split.values
train_df[sensitive] = s_train_split.values

train_ds = StandardDataset(
    train_df,
    label_name=target, # the column with labels (0/1)
    favorable_classes=[1], # value considered positive
    protected_attribute_names=[sensitive], # or ['race'], etc.
    privileged_classes=[[1]] # e.g., male if 1 = male
)

In [139]:
test_df = X_test_split.copy()
test_df[target] = y_test_split.values
test_df[sensitive] = s_test_split.values

test_ds = StandardDataset(
    test_df,
    label_name=target, # the column with labels (0/1)
    favorable_classes=[1], # value considered positive
    protected_attribute_names=[sensitive], # or ['race'], etc.
    privileged_classes=[[1]] # e.g., male if 1 = male
)

In [140]:
predictions = {}

### Pre-Processing

In [141]:
cr = CorrelationRemover(sensitive_feature_ids=[sensitive], alpha=1)

X_train_cr = cr.fit_transform(train_df)
X_train_cr_df = pd.DataFrame(X_train_cr)

X_test_cr = cr.transform(test_df)
X_test_cr_df = pd.DataFrame(X_test_cr)

In [142]:
def create_model(seed, input_dim):
    tf.random.set_seed(seed)
    model = Sequential()
    model.add(Dense(128, input_dim=input_dim, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dense(128, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dense(128, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dense(64, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dense(1, activation='sigmoid'))

    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

models = {
    'Logistic Regression': LogisticRegression(),
    'Linear Regression': LinearRegression(),
    'Decision Tree': DecisionTreeClassifier(),
    'Naive Bayes': GaussianNB(),
    'XGBoost': XGBClassifier(),
    'KNN': KNeighborsClassifier(),
    'Neural Network': create_model(random_seed, X_train_cr_df.shape[1]),
}

In [143]:
for model_name, model in models.items():
    print(f"Training {model_name}...")
    if model_name == 'Neural Network':
        model.fit(X_train_cr_df, y_train_split, epochs=10, batch_size=32, verbose=0)
        predictions[f"{model_name}_preprocessed_cr"] = model.predict(X_test_cr_df).flatten()
    else:
        model.fit(X_train_cr_df, y_train_split)
        predictions[f"{model_name}_preprocessed_cr"] = model.predict(X_test_cr_df)

    if model_name in ['Linear Regression', 'XGBoost', 'Neural Network']:
        predictions[f"{model_name}_preprocessed_cr"] = (predictions[f"{model_name}_preprocessed_cr"] > 0.5).astype(int)
    
    print(f"{model_name} trained.")
    temp = predictions[f"{model_name}_preprocessed_cr"]
    print(f"Preprocessed predictions for {model_name}: {temp}")

Training Logistic Regression...

c:\Users\andre\Desktop\ProjectWork_AEQUITAS_AKKODIS\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression trained.
Preprocessed predictions for Logistic Regression: [0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 1 0 1 1 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1
 1 0 0 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 0 0 0 1 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 1
 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1
 1 0 0 0 0 1 1 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 1 0 0 1
 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0
 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0
 0 1 0 0 0 0 1 0 0 0 0 1 1 1 1 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0]
Training Linear Regression...
Linear Regression trained.
Preprocessed predictions for Linear Regression: [0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 1 0 1 0 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1
 1 0 0 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 1
 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1
 1 1 0 0 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0 1
 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0
 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0
 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0]
Training Decision Tree...
Decision Tree trained.
Preprocessed predictions for Decision Tree: [0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 1 0 1 0 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1
 1 0 0 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 1
 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1
 1 1 0 0 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0 1
 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0
 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0
 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0]
Training Naive Bayes...
Naive Bayes trained.
Preprocessed predictions for Naive Bayes: [0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 1 0 1 0 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1
 1 0 0 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 1
 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1
 1 1 0 0 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0 1
 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0
 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0
 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0]
Training XGBoost...
XGBoost trained.
Preprocessed predictions for XGBoost: [0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 1 0 1 0 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1
 1 0 0 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 1
 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1
 1 1 0 0 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0 1
 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0
 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0
 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0]
Training KNN...
KNN trained.
Preprocessed predictions for KNN: [0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 1 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0
 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 1 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0
 0 1 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0]
Training Neural Network...
17/17 [==============================] - 0s 4ms/step
Neural Network trained.
Preprocessed predictions for Neural Network: [0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1
 0 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1
 0 1 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 0
 1 0 1 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 1 0
 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0]

### In-Processing

In [144]:
models = {
    'Linear Regression': LinearRegression(),
}

In [145]:
for model_name, model in models.items():
    gfc = GerryFairClassifier(
        C=10,
        gamma=0.01,
        fairness_def='FP',
        max_iters=10,
        printflag=False,
        heatmapflag=False,
        heatmap_iter=10,
        heatmap_path='.',
        predictor=model
    )
    gfc.fit(train_ds)
    pred_gfc = gfc.predict(test_ds)
    predictions[f"{model_name}_inprocessed_gfc"] = pred_gfc.labels.ravel()
    temp = predictions[f"{model_name}_inprocessed_gfc"]
    print(f"Inprocessed predictions for {model_name}: {temp}")

Inprocessed predictions for Linear Regression: [0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1
 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0
 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 1 0
 0 1 0 0 0 0 1 0 0 0 0 0 1 1 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0]

### Post-Processing

In [146]:
def create_model(seed, input_dim):
    tf.random.set_seed(seed)
    model = Sequential()
    model.add(Dense(128, input_dim=input_dim, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dense(128, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dense(128, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dense(64, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dense(1, activation='sigmoid'))

    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

models = {
    'Logistic Regression': LogisticRegression(),
    'Linear Regression': LinearRegression(),
    'Decision Tree': DecisionTreeClassifier(),
    'Naive Bayes': GaussianNB(),
    'XGBoost': XGBClassifier(),
    'KNN': KNeighborsClassifier(),
    'Neural Network': create_model(random_seed, train_df.shape[1]),
}

In [147]:
for model_name, model in models.items():
    print(f"Training {model_name}...")
    if model_name == 'Neural Network':
        model.fit(train_df, y_train_split, epochs=10, batch_size=32, verbose=0)
        predictions[f"{model_name}_postprocessed_to"] = model.predict(test_df).flatten()
    else:
        model.fit(train_df, y_train_split)
        predictions[f"{model_name}_postprocessed_to"] = model.predict(test_df)

    print(f"{model_name} trained.")

Training Logistic Regression...
Logistic Regression trained.
Training Linear Regression...
Linear Regression trained.
Training Decision Tree...
Decision Tree trained.
Training Naive Bayes...
Naive Bayes trained.
Training XGBoost...

c:\Users\andre\Desktop\ProjectWork_AEQUITAS_AKKODIS\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

XGBoost trained.
Training KNN...
KNN trained.
Training Neural Network...
17/17 [==============================] - 1s 5ms/step
Neural Network trained.

In [148]:
for model_name, model in models.items():
    to = ThresholdOptimizer(
        estimator=model,
        constraints='demographic_parity',
        objective='accuracy_score',
        prefit=True,
        grid_size=1000,
        flip=False,
        predict_method='predict'
    )
    to.fit(train_df, y_train_split, sensitive_features=s_train_split)
    pred_to = to.predict(test_df, sensitive_features=s_test_split)
    predictions[f"{model_name}_postprocessed_to"] = pred_to.ravel()
    temp = predictions[f"{model_name}_postprocessed_to"]
    print(f"Postprocessed predictions for {model_name}: {temp}")

Postprocessed predictions for Logistic Regression: [0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 1 0 0 0 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1
 1 0 0 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 0 0 0 1 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 1
 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1
 1 1 0 0 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0 1
 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0
 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0
 0 1 0 0 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0]
Postprocessed predictions for Linear Regression: [0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 0 0 0 0 1 0 1 1 1 0 1 0 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1
 1 0 0 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 1
 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1
 1 1 0 0 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0 1
 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0
 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0
 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0]
Postprocessed predictions for Decision Tree: [0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 1 0 1 0 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1
 1 0 0 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 1
 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1
 1 0 0 0 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0 1
 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0
 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0
 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0]
Postprocessed predictions for Naive Bayes: [0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 1 0 1 0 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1
 1 0 0 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 1
 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1
 1 1 0 0 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0 1
 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0
 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0
 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0]
Postprocessed predictions for XGBoost: [0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 1 0 1 0 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1
 1 0 0 0 1 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 1
 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1
 1 1 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0 1
 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0
 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0
 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0]
Postprocessed predictions for KNN: [0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 1 1 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1
 0 0 1 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 1 1 0 0 0 1 0 0 1 0 0 0 0
 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0
 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0
 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0]

c:\Users\andre\Desktop\ProjectWork_AEQUITAS_AKKODIS\.venv\lib\site-packages\fairlearn\postprocessing\_threshold_optimizer.py:309: UserWarning: The value of `prefit` is `True`, but `check_is_fitted` raised `NotFittedError` on the base estimator.

If the provided base estimator has been fitted, this could mean that (1) its implementation does not conform to the sklearn estimator API, or (2) the enclosing ThresholdOptimizer has been cloned (for instance by `sklearn.model_selection.cross_validate`).

In case (1), please file an issue with the base estimator developers, but continue to use the enclosing ThresholdOptimizer with `prefit=True`. In case (2), please use `prefit=False`.
  warn(BASE_ESTIMATOR_NOT_FITTED_WARNING.format(type(self).__name__))

65/65 [==============================] - 0s 4ms/step
 1/17 [>.............................] - ETA: 1s

c:\Users\andre\Desktop\ProjectWork_AEQUITAS_AKKODIS\.venv\lib\site-packages\fairlearn\postprocessing\_interpolated_thresholder.py:107: UserWarning: The value of `prefit` is `True`, but `check_is_fitted` raised `NotFittedError` on the base estimator.

If the provided base estimator has been fitted, this could mean that (1) its implementation does not conform to the sklearn estimator API, or (2) the enclosing InterpolatedThresholder has been cloned (for instance by `sklearn.model_selection.cross_validate`).

In case (1), please file an issue with the base estimator developers, but continue to use the enclosing InterpolatedThresholder with `prefit=True`. In case (2), please use `prefit=False`.
  warn(BASE_ESTIMATOR_NOT_FITTED_WARNING.format(type(self).__name__))

17/17 [==============================] - 0s 8ms/step
Postprocessed predictions for Neural Network: [0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 1 0 1 0 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1
 1 0 0 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 1
 0 0 1 1 0 0 0 0 1 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1
 1 1 0 0 0 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0 1
 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 0 1 0 0 1 0 0 0
 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0
 0 1 0 0 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0]

## Save

In [149]:
reference = {}
for model_name, preds in predictions.items():
    reference[model_name] = y_test_split.values

data = pd.DataFrame({
    'predictions': predictions,
    'reference':   reference,
})
data.head(50)

,predictions,reference
Logistic Regression_preprocessed,"[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ..."
Linear Regression_preprocessed,"[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ..."
Decision Tree_preprocessed,"[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ..."
Naive Bayes_preprocessed,"[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ..."
XGBoost_preprocessed,"[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ..."
KNN_preprocessed,"[0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ..."
Neural Network_preprocessed,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ..."
Linear Regression_inprocessed_gfc,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ..."
Logistic Regression_postprocessed_to,"[0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ..."
Linear Regression_postprocessed_to,"[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ..."
Decision Tree_postprocessed_to,"[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ..."
Naive Bayes_postprocessed_to,"[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ..."
XGBoost_postprocessed_to,"[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ..."
KNN_postprocessed_to,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ..."
Neural Network_postprocessed_to,"[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, ..."

In [150]:
data.to_excel(PATH + 'data/predictions.xlsx', index=False)